package com.enmanuelbergling.ktormovies.ui.theme
import androidx.compose.ui.graphics.Color

val Gold = Color(0xFFFFAA1C)

val md_theme_light_primary = Color(0xFF914C00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCC4)
val md_theme_light_onPrimaryContainer = Color(0xFF2F1500)
val md_theme_light_secondary = Color(0xFFAB3600)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCF)
val md_theme_light_onSecondaryContainer = Color(0xFF390C00)
val md_theme_light_tertiary = Color(0xFF00629E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCFE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D34)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A17)
val md_theme_light_surfaceVariant = Color(0xFFF3DFD2)
val md_theme_light_onSurfaceVariant = Color(0xFF51443B)
val md_theme_light_outline = Color(0xFF847469)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEE8)
val md_theme_light_inverseSurface = Color(0xFF352F2B)
val md_theme_light_inversePrimary = Color(0xFFFFB77F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF914C00)
val md_theme_light_outlineVariant = Color(0xFFD6C3B7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB77F)
val md_theme_dark_onPrimary = Color(0xFF4E2600)
val md_theme_dark_primaryContainer = Color(0xFF6F3900)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC4)
val md_theme_dark_secondary = Color(0xFFFFB59C)
val md_theme_dark_onSecondary = Color(0xFF5C1900)
val md_theme_dark_secondaryContainer = Color(0xFF822700)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCF)
val md_theme_dark_tertiary = Color(0xFF9ACBFF)
val md_theme_dark_onTertiary = Color(0xFF003355)
val md_theme_dark_tertiaryContainer = Color(0xFF004A78)
val md_theme_dark_onTertiaryContainer = Color(0xFFCFE5FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A17)
val md_theme_dark_onBackground = Color(0xFFECE0DA)
val md_theme_dark_surface = Color(0xFF201A17)
val md_theme_dark_onSurface = Color(0xFFECE0DA)
val md_theme_dark_surfaceVariant = Color(0xFF51443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C3B7)
val md_theme_dark_outline = Color(0xFF9E8D82)
val md_theme_dark_inverseOnSurface = Color(0xFF201A17)
val md_theme_dark_inverseSurface = Color(0xFFECE0DA)
val md_theme_dark_inversePrimary = Color(0xFF914C00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB77F)
val md_theme_dark_outlineVariant = Color(0xFF51443B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFF98E27)
